version: "3.9"

services:

  unityadapter:
    image: mosim01/mosim:unityadapter
    ports:
        - ${UnityAdapter}:${DOCKER_STDP}
    command: [ "Adapter" , "${MIPA}" , "${DOCKER_STDP}" , "${UnityAdapter}" , "${LAUNCHER_IPP}" ]
    
  csharpadapter:
    image: mosim01/mosim:csharpadapter
    ports:
        - ${CSharpAdapter}:${DOCKER_STDP}
    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${CSharpAdapter}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - unityadapter
    
#  cosimulation:
#    build: CoSimulation
#    ports:
#        - ${CoSimulation}:${DOCKER_STDP}
#        - ${CoSimulationServ}:${DOCKER_STDP2}
#    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${DOCKER_STDP2}" , "${CoSimulation}" , "${CoSimulationServ}" , "${LAUNCHER_IPP}" ]
#    depends_on:
#        - csharpadapter

#  blenderik:
#    build: BlenderIK
#    ports:
#        - ${BlenderIK}:${DOCKER_STDP}
#    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${BlenderIK}" , "${LAUNCHER_IPP}" ]

  coordinatesystemmapper:
    image: mosim01/mosim:coordinatesystemmapper
    ports:
        - ${CoordinateSystemMapper}:${DOCKER_STDP}
    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${CoordinateSystemMapper}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - csharpadapter


  postureblendingservice:
    image: mosim01/mosim:postureblendingservice
    ports:
        - ${PostureBlendingService}:${DOCKER_STDP}
    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${PostureBlendingService}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - csharpadapter

  retargetingservice:
    image: mosim01/mosim:retargetingservice
    ports:
        - ${RetargetingService}:${DOCKER_STDP}
    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${RetargetingService}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - csharpadapter

  skeletonaccessservice:
    image: mosim01/mosim:skeletonaccessservice
    ports:
        - ${SkeletonAccessService}:${DOCKER_STDP}
    command: [ "${MIPA}" , "${DOCKER_STDP}" , "${SkeletonAccessService}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - csharpadapter

  unitypathplanning:
    image: mosim01/mosim:unitypathplanning
    ports:
        - ${UnityPathPlanningService}:${DOCKER_STDP}
    command: [ "PathPlanningService" , "${MIPA}" , "${DOCKER_STDP}" , "${UnityPathPlanningService}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - unityadapter

  unityikservice:
    image: mosim01/mosim:unityikservice
    ports:
        - ${UnityIKService}:${DOCKER_STDP}
    command: [ "IKService" , "${MIPA}" , "${DOCKER_STDP}" , "${UnityIKService}" , "${LAUNCHER_IPP}" ]
    depends_on:
        - unityadapter

