version: "3.9"

services:
  cosimulation:
    build: CSharp
    image: ${CSHARP_IMAGE}
    ports:
        - ${CoSimulation}:${DOCKER_STDP}
        - ${CoSimulationServ}:${DOCKER_STDP2}
    command: [ "CoSimulation" , "${MIPA}" , "${DOCKER_STDP}" , "${CoSimulation}" ,  "${LAUNCHER}" , "${DOCKER_STDP2}" , "${CoSimulationServ}" ]

