version: "3.9"

services:
  csharpadapter:
    build: CSharp
    image: ${CSHARP_IMAGE}
    ports:
        - ${CSharpAdapter}:${DOCKER_STDP}
    stdin_open: true
    tty: true 
    command: [ "CSharpAdapter" , "${MIPA}" , "${DOCKER_STDP}" , "${CSharpAdapter}" , "${LAUNCHER_IPP}" ]