version: "3.9"

services:

  launcher:
    build: CSharp
    image: ${CSHARP_IMAGE}
    stdin_open: true
    tty: true
    ports:
        - ${LAUNCHER}:${DOCKER_STDP}
    command: [ "Launcher" , "${MIPA}" , "${DOCKER_STDP}" ]
    volumes:
        - /home/kuf/data:/data
